### ISSUE TITLE
Issues with negative values in pixel calibration

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/bigdataviewer-spimdata-extras#3]
Hi @tischi, 

I have issues with negative calibration values in ImagePlus. It's not well supported and causes exception with multiple ij1 plugins.

I don't know what's the best to handle this. Maybe flipping the image itself before saving it.

**Comment by tischi** [comment]
I guess it would be important that the physical space coordinates show up negative, isn't it? Then maybe flipping in data space combined with a negative offset in the calibration? 

In general, I think that's also something you could ask on the forum and ping Wayne.

**Comment by NicoKiaru** [comment]
FYI the OME model does not allow negative numbers, that's when I notice the problem.

I think ideally we should flip the image with Views in https://github.com/BIOP/bigdataviewer-spimdata-extras/blob/d833c34cca4ae008038a537527fd7eff0da68b71/src/main/java/spimdata/imageplus/ImagePlusHelper.java#L309 when we detect that the axis are not in the correct orientation, and thus keep the calibration positive (we would need to redefine the origin, by computing the new offset).

**Comment by NicoKiaru** [comment]
I think this issue is not longer relevant - or at least it needs to be moved because this functionality has moved to a different repo
