### ISSUE TITLE
main integration branch

### ISSUE THREAD

**Issue by ctrueden** [BIOP/bigdataviewer-spimdata-extras#5]
@NicoKiaru Just a heads up that this repo has both `master` and `main` integration branches, with `main` being stuck at the initial commit. If you intend to keep the integration branch named `master`, I suggest deleting the `main` branch because some tooling will get confused when both exist—e.g. my `gcm` alias checks out `main` preferentially over `master` because that's the more recent best practice. Or if you want to migrate to `main`, you can delete `main`, the rename `master` to `main` in the web UI, then run [this script](https://github.com/ctrueden/dotfiles/blob/2f32d1f6a0e8483a9401ae6ec6fa2c580c54dba0/bin/master-to-main) in your local working copy.

**Comment by NicoKiaru** [comment]
Ah yes, thanks! I've deleted main for now. I'll migrate in mass to main all repos another time.
